export const myProjects = [
  {
    title: "Bien naître et Bien être",
    id: 1,
    url: "https://site-virginie-perrault-v2.vercel.app/",
    gitHub: "https://github.com/RaspberryChaos/next-site-virginie-perrault/blob/main/README.md",
    category: "Client project",
    tags: ["HTML", "CSS", "JavaScript", "React", "Next.js"],
    img: "/siteVP1.jpg",
  },
  {
    title: "Trivia Game",
    id: 2,
    url: "https://trivia-app-ailie.vercel.app/",
    gitHub: "https://github.com/RaspberryChaos/trivia-app",
    category: "React Game",
    tags: [
      "HTML",
      "CSS",
      "JavaScript",
      "React",
      "TypeScript",
      "Next.js",
      "API",
    ],
    img: "/trivia.jpg",
  },
  {
    title: "Whale Of Fortune",
    id: 3,
    url: "https://raspberrychaos.github.io/game-project/",
    gitHub: "https://github.com/RaspberryChaos/game-project",
    category: "Ironhack student project",
    tags: ["HTML", "CSS", "JavaScript"],
    img: "/WoF2.jpg",
  },
  {
    title: "My Life Timeline",
    id: 4,
    url: "http://my-timeline-project.herokuapp.com/",
    gitHub: "https://github.com/KiwiMantelli/my-timeline-project2",
    category: "Ironhack student project",
    tags: [
      "HTML",
      "CSS",
      "JavaScript",
      "Node",
      "Express",
      "Handlebars",
      "MongoDB",
      "Mongoose",
    ],
    img: "/timeline1.jpg",
  },
  {
    title: "Breakroom 248",
    id: 5,
    url: "http://breakroom-248.herokuapp.com/",
    gitHub: "https://github.com/tatimatz/breakroom248client/tree/master",
    category: "Ironhack student project",
    tags: [
      "HTML",
      "CSS",
      "JavaScript",
      "React",
      "Node",
      "Express",
      "MaterialUI",
      "MongoDB",
      "Mongoose",
    ],
    img: "/breakroom1.jpg",
  },
  {
    title: "Calculator",
    id: 6,
    url: "https://ailie-mccorkindale.vercel.app/mini-projects/calculator",
    gitHub: "https://github.com/RaspberryChaos/my-portfolio/blob/main/pages/mini-projects/calculator.js",
    category: "Mini Project",
    tags: ["HTML", "CSS", "JavaScript", "React", "Next.js"],
    img: "/calculator.jpg",
  },
  {
    title: "Currency Converter",
    id: 7,
    url: "https://ailie-mccorkindale.vercel.app/mini-projects/currency-converter",
    gitHub: "https://github.com/RaspberryChaos/my-portfolio/blob/main/pages/mini-projects/currency-converter.js",
    category: "Mini Project",
    tags: ["HTML", "CSS", "JavaScript", "React", "Next.js", "API"],
    img: "/currencyConverter.jpg",
  },
  {
    title: "Flappy Bird",
    id: 8,
    url: "https://flappybird-ailie.netlify.app/",
    gitHub: "https://github.com/RaspberryChaos/flappy-bird",
    category: "HTML Canvas Game",
    tags: ["HTML", "CSS", "JavaScript"],
    img: "/flappybird1.jpg",
  },
  {
    title: "Bubble Pop",
    id: 9,
    url: "https://bubblepop-ailie.netlify.app/",
    gitHub: "https://github.com/RaspberryChaos/bubblePop",
    category: "HTML Canvas Game",
    tags: ["HTML", "CSS", "JavaScript"],
    img: "/bubblePop1.jpg",
  },
  {
    title: "Fake Shop",
    id: 10,
    url: "https://fake-shop-ailie.netlify.app/",
    gitHub: "https://github.com/RaspberryChaos/fake-shop",
    category: "Mini Project",
    tags: ["React", "Redux", "HTML", "CSS", "JavaScript", "Bootstrap", "API"],
    img: "/fakeShop.jpg",
  },
];
