import Head from 'next/head';


export default function Home() {
  return (
    <div className="container">
      <Head>
        <title>Portfolio</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      <main className="main">
      <h1>My Portfolio</h1>
        <p>Main Content</p>
      </main>

      <footer className="footer">
        <p>Footer</p>
      </footer>
    </div>
  )
}
